In [7]:
import numpy as np
import pandas
import matplotlib.pyplot

a = np.ones((4, 4))
b = a * 5

b = b.reshape(2, 8)

print(a)
print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5.]]
